### PR TITLE
Iss1393: UI Settings for more cutomizability

### LINKED ISSUE #1393: Display Settings For Correct Answer
Is there a way through the uiSettings to make the extra feedback for the correct answer not display? It would be nice to have it only say "correct" when the answer is correct and the additional details when the answer is incorrect.
image

### PR DESCRIPTION
**Pull request by JRustyHaner**
Fixes #1393 

New Specs for UISettings @imrryr 

onlyShowSimpleFeedback ("onCorrect" | "onIncorrect" | true | false, default: onCorrect): Reduces feedback to just the word "Correct" or "Incorrect". This is controllable to trigger during correct response feedback using the "onCorrect" setting. Inversely, this can be set to "onIncorrect" to trigger only during incorrect response feedback. True enables both, and false enables neither setting. 

displayUserAnswerInFeedback  ("onCorrect" | "onIncorrect" | true | false, default: onIncorrect): This prepends the user answer in the feedback. This is controllable to trigger during correct response feedback using the "onCorrect" setting. Inversely, this can be set to "onIncorrect" to trigger only during incorrect response feedback. True enables both, and false enables neither setting.

### CODE REVIEW

File: mofacts/client/views/experiment/card.js [hunk 1]
```diff
@@ -1579,7 +1578,7 @@ async function showUserFeedback(isCorrect, feedbackMessage, afterAnswerFeedbackC
         feedbackMessage = "<b style='color:" + uiIncorrectColor + ";'>Incorrect.</b><br>" + feedbackMessage;
```
Comment (imrryr) [inline mofacts/client/views/experiment/card.js:1578]: this is not that easy to maintain or understand... also isn't it redundant with the new code? Can we strip it out safely

Comment (imrryr) [reply mofacts/client/views/experiment/card.js:1578]: this is 1573 to 1579. I can now set this with displayUserAnswerInFeedback

File: mofacts/client/views/experiment/card.js [hunk 2]
```diff
@@ -1588,6 +1587,14 @@ async function showUserFeedback(isCorrect, feedbackMessage, afterAnswerFeedbackC
...
       }
     }
+    if(Session.get('curTdfUISettings').displayUserAnswerInIncorrectFeedback && !isCorrect){
+      //prepend the user answer to the feedback message
+      if(singleLineFeedback){
+        feedbackMessage =  "Your answer: " + userAnswer + '. ' + feedbackMessage;
+      } else {
+        feedbackMessage = "<br>Your answer: " + userAnswer + '. ' + feedbackMessage;
+      }
+    }
```
Comment (imrryr) [inline mofacts/client/views/experiment/card.js:1597]: OK, so this seems redundant for iscorrect and !iscorrect isn't it doing the same thing?

**Review by imrryr — COMMENTED** [review]
Please look at my comments @JRustyHaner

File: mofacts/client/views/experiment/card.js (hunk 2 above)
Comment (imrryr) [reply mofacts/client/views/experiment/card.js:1597]: sorry, talkign abotu lines 1585 -1590 and 1592 -1597

Comment (JRustyHaner) [reply mofacts/client/views/experiment/card.js:1597]: @imrryr it's supposed to read in 1581 displayUserCorrectFeedback. I changed it

Comment (imrryr) [reply mofacts/client/views/experiment/card.js:1589]: Like these changes!

File: mofacts/client/views/experiment/card.js (hunk 1 above)
Comment (imrryr) [reply mofacts/client/views/experiment/card.js:1578]: @JRustyHaner @MegaGeese Still wondering about 1573-1579... please explain when they are needed. I don't see why I want to make timeouts different, but only when in the center. Why is this?
